import {listRecords,saveRecord} from '@/lib/persistence';
import {evaluate} from '@/lib/review-engine';
import {Brand,Asset,Review,categories} from '@/lib/types';
import {sampleBrand} from '@/lib/sample';
export async function GET(){try{return Response.json({brands:await listRecords('brand'),reviews:await listRecords('review')});}catch(e){console.error(e);return Response.json({error:'Saved workspace could not be loaded. Retry shortly.'},{status:503});}}
export async function POST(request:Request){try{if(Number(request.headers.get('content-length')??0)>1500000)return Response.json({error:'Request too large.'},{status:413});const data=await request.json() as {action:string;brand:Brand;brandId:string;asset:Asset;reviewId:string;findingId:string;decision:"accepted"|"rejected"};
 if(data.action==='brand'){const b=data.brand as Brand;if(!b?.id||!b.name?.trim()||!Array.isArray(b.rules)||!Array.isArray(b.guidelines)||b.rules.length>200)throw new Error('Enter a brand name and valid rules.');if(categories.some(c=>!Number.isFinite(b.weights[c])||b.weights[c]<0)||Object.values(b.weights).reduce((a,n)=>a+n,0)<=0)throw new Error('Scoring weights must be non-negative with a positive total.');await saveRecord('brand',b);return Response.json({brand:b});}
 if(data.action==='review'){const brand=(await listRecords('brand')).find(b=>b.id===data.brandId)??(data.brandId===sampleBrand.id?sampleBrand:null);if(!brand)throw new Error('Choose a saved brand.');const asset=data.asset as Asset;if(!asset?.name?.trim()||!Array.isArray(asset.sections)||!asset.sections.some(s=>s.text.trim()))throw new Error('Add readable asset content.');const review=await evaluate(brand,asset);await saveRecord('review',review);return Response.json({review});}
 if(data.action==='decision'){const review=(await listRecords('review')).find(r=>r.id===data.reviewId) as Review|undefined;if(!review||!['accepted','rejected'].includes(data.decision))throw new Error('Review or decision is invalid.');const finding=review.findings.find(f=>f.id===data.findingId);if(!finding)throw new Error('Finding not found.');finding.decision=data.decision;await saveRecord('review',review);return Response.json({review});}throw new Error('Unknown action.');
 }catch(e){console.error(e);return Response.json({error:e instanceof Error?e.message:'Unable to save. Your input has been preserved.'},{status:400});}}
